apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
  namespace: sonatype
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - image: sonatype/nexus3
        imagePullPolicy: Always
        name: nexus
        ports:
        - containerPort: 8081
        volumeMounts:
          - mountPath: /nexus-data
            name: nexus-data
      volumes:
        - name: nexus-data
          hostPath:
            path: /Users/kit/Dropbox/Workspace/sonatype_k8s/nexus-data
            type: DirectoryOrCreate
